FROM  ubuntu:14.04

LABEL maintainer="LiuGaoyong <liugaoyong_88@163.com>"

RUN add-apt-repository ppa:campos-dev/campos && apt-get update &&\
	apt-get install gazpacho gfortran python-dev \
                     python-glade2 python-kiwi python-lxml \
                     python-matplotlib python-numpy python-ase \
                     python-pygoocanvas git &&\
    #git clone http://www.github.com/mhoffman/kmos kmos
